import { expect, test } from "@playwright/test";
test("homepage introduces Jiahui and links to every page", async ({ page }) => { await page.goto("/"); await expect(page.getByRole("heading", { level: 1 })).toHaveText("Jiahui Chen"); await expect(page.getByText("software engineer in Tokyo")).toBeVisible(); const nav = page.getByRole("navigation", { name: "Site" }); await expect(nav.getByRole("link", { name: "Work" })).toHaveAttribute("href", "/work/"); await expect(nav.getByRole("link", { name: "Projects" })).toHaveAttribute("href", "/projects/"); await expect(nav.getByRole("link", { name: "Résumé" })).toHaveAttribute("href", "/josh-chen-resume.pdf"); });
test("work page lists experience, education, and skills", async ({ page }) => { await page.goto("/work/"); await expect(page.getByRole("heading", { level: 1 })).toHaveText("Work"); await expect(page.getByRole("heading", { name: /ORCA Co., Ltd./ })).toBeVisible(); for (const name of ["Education", "Service", "Skills"]) await expect(page.getByRole("heading", { name, exact: true })).toBeVisible(); await expect(page.getByRole("link", { name: "Work" })).toHaveAttribute("aria-current", "page"); });
test("projects page links each project to its repository", async ({ page }) => { await page.goto("/projects/"); await expect(page.getByRole("heading", { level: 1 })).toHaveText("Projects"); await expect(page.getByRole("article")).toHaveCount(3); await expect(page.getByRole("link", { name: "DevOps with Kubernetes" })).toHaveAttribute("href", /github\.com\/joshchen-dev/); });
test("theme toggle switches to dark mode", async ({ page }) => { await page.goto("/"); const toggle = page.getByRole("button", { name: "Toggle color theme" }); await expect(toggle).toHaveAttribute("data-hydrated", "true"); await toggle.click(); await expect(page.locator("html")).toHaveClass(/dark/); });
test("small text stays readable", async ({ page }) => { for (const [path, selectors] of [["/", [".home-aside", ".home-contact"]], ["/work/", [".when", ".label", ".words", ".site-footer"]]] as const) { await page.goto(path); for (const selector of selectors) { const element = page.locator(selector).first(); await expect(element).toBeVisible(); const size = await element.evaluate((node) => Number.parseFloat(getComputedStyle(node).fontSize)); expect(size, `${path} ${selector} font size`).toBeGreaterThanOrEqual(14); } } });
test("entrance animation settles with every block fully visible", async ({ page }) => { for (const [path, selector] of [["/", ".home > *"], ["/work/", ".tech-main > *"], ["/projects/", ".tech-main > *"]] as const) { await page.goto(path); const blocks = page.locator(selector); const count = await blocks.count(); expect(count).toBeGreaterThan(2); for (let i = 0; i < count; i++) await expect(blocks.nth(i)).toHaveCSS("opacity", "1"); } });
test("reduced motion renders content without animating", async ({ page }) => { await page.emulateMedia({ reducedMotion: "reduce" }); await page.goto("/work/"); const styles = await page.locator(".tech-main > *").evaluateAll((nodes) => nodes.map((node) => ({ opacity: getComputedStyle(node).opacity, animation: getComputedStyle(node).animationName }))); expect(styles.every(({ opacity, animation }) => opacity === "1" && animation === "none")).toBe(true); });
test("navigating between pages lands on a fully visible page", async ({ page }) => { await page.goto("/"); await page.getByRole("navigation", { name: "Site" }).getByRole("link", { name: "Work" }).click(); await expect(page).toHaveURL(/\/work\/$/); await expect(page.getByRole("heading", { level: 1 })).toHaveText("Work"); await page.getByRole("link", { name: "Projects" }).click(); await expect(page).toHaveURL(/\/projects\/$/); await expect(page.getByRole("heading", { level: 1 })).toHaveText("Projects"); await expect(page.locator(".tech-main > *").last()).toHaveCSS("opacity", "1"); });
